### ISSUE TITLE
[Bug] Type Grouping Causes Duplicate Definitions of Common Variables

### ISSUE THREAD

**Issue by ruikc** [zeromicro/go-zero#4842]
**Describe the bug**
创建一个user.api放所有共用的请求与返回的结构体。比如UserLoginResp
在app分组中，路由express/info，使用返回数据为UserLoginResp ，在public分组中，路由/user/login返回也是UserLoginResp，1.8.2版本中在types中只会定义一个UserLoginResp结构体，可以正常使用，升级到1.8.3后，会在app.go与public.go都生成UserLoginResp结构体，并且都在types包下，直接报变量重复定义。
这样导致的问题就是必须给每个分组指定相同结构，但名称不同的结构？

Create a `user.api` to hold all the common request and response structures, such as `UserLoginResp`. In the `app` group, the route `express/info` uses the `UserLoginResp` as the return data. In the `public` group, the route `/user/login` also returns `UserLoginResp`. In version 1.8.2, only one `UserLoginResp` structure is defined in `types`, and it can be used normally. However, after upgrading to 1.8.3, `UserLoginResp` structures are generated in both `app.go` and `public.go`, and they are all under the `types` package, resulting in a variable redefinition error. This leads to the problem that the same structure with different names must be specified for each group.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is
 ```
@server (
	prefix:     /app
	group:      app
	middleware: AppMiddleware
)
service server-api {
	@handler ExpressInfo
	get /express/info returns (UserLoginResp)

}
@server (
	group: public
)
service server-api {
	@handler UserLogin
	post /user/login (UserLoginReq) returns (UserLoginResp)
}
   
 ```

2. The error is
```
UserLoginResp redeclared in this blockcompiler[DuplicateDecl](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#DuplicateDecl)
app.go(383, 6): other declaration of UserLoginResp
```

**Expected behavior**
可以分组，但要考虑到公共变量的使用，如果因为必须分组导致重复创个结构体感觉得不偿失，或者在goctl添加个参数，让用户控制

Grouping can be done, but the usage of public variables should be taken into account. If creating a new structure due to mandatory grouping leads to a sense of not being worth the effort, or if a parameter can be added in goctl to allow users to control it.

**Screenshots**

![Image](https://github.com/user-attachments/assets/348d39b3-9113-41d2-9ccc-4e011ef7e49e)

![Image](https://github.com/user-attachments/assets/3b4253e0-dbe2-4096-b304-45f4ecb3caec)

**Environments (please complete the following information):**
 - OS: [e.g. Linux] macos
 - go-zero version [e.g. 1.2.1] 1.8.3
 - goctl version [e.g. 1.2.1, optional] 1.8.3

**More description**

**Comment by ruikc** [comment]
![Image](https://github.com/user-attachments/assets/ade77647-b9d7-4aa8-ac7f-d64198f2e56b)

![Image](https://github.com/user-attachments/assets/e077315d-7f8a-4142-9694-8428d40ec12f)

![Image](https://github.com/user-attachments/assets/fc28abe3-c8b8-4e4c-ba1d-2051940b4556)

![Image](https://github.com/user-attachments/assets/4479669b-2c1b-41a7-9064-0a3eb2bb4ef1)

default is off ,why I gen use group? and i set the env is off ,still gen go as group

**Comment by jaronnie** [comment]
please use `goctl env -w GOCTL_EXPERIMENTAL=off`

**Comment by kevwan** [comment]
# English Translation of Issue #4842: Type Grouping Causes Duplicate Definition of Common Variables

## Bug Description
After upgrading from go-zero v1.8.2 to v1.8.3, there's an issue with the new API type grouping feature that causes duplicate definitions of shared structures.

### Scenario
- A `user.api` file contains common request and response structures (e.g., `UserLoginResp`)
- In the `app` group with route `express/info`, this structure is used as a return type
- In the `public` group with route `/user/login`, the same structure is also used
- **In v1.8.2**: Only one `UserLoginResp` structure would be generated in the `types` package
- **In v1.8.3**: The structure is duplicated in both `app.go` and `public.go` under the same `types` package, causing compilation errors due to duplicate definition

### Reproduction Steps

API definition:
```
@server (
	prefix:     /app
	group:      app
	middleware: AppMiddleware
)
service server-api {
	@handler ExpressInfo
	get /express/info returns (UserLoginResp)
}

@server (
	group: public
)
service server-api {
	@handler UserLogin
	post /user/login (UserLoginReq) returns (UserLoginResp)
}
```

Error received:
```
UserLoginResp redeclared in this block
compiler[DuplicateDecl](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#DuplicateDecl)
app.go(383, 6): other declaration of UserLoginResp
```

### Expected Behavior
The ability to use grouping while still maintaining shared structures without duplication. Current behavior forces developers to create duplicate structures with different names for each group, which is inefficient.

### Workaround
As noted in the comments, you can disable the experimental features with:
```
goctl env -w GOCTL_EXPERIMENTAL=off
```

### Environment
- OS: macOS
- go-zero version: 1.8.3
- goctl version: 1.8.3

---

*Note: This issue appears to be related to the new type grouping feature mentioned in the v1.8.3 release notes under "Experimental Features" that splits API type structures based on group names.*

**Comment by kesonan** [comment]
it will be fixed on pr #4849
