### ISSUE TITLE
goctl v1.10.1 does not generate client aliases for nested message types used by service responses

### ISSUE THREAD

**Issue by dbirder** [zeromicro/go-zero#5618]
## Describe the bug

After upgrading `goctl` from v1.9.x to v1.10.1, the generated RPC client no longer contains type aliases for message types that are used inside RPC request/response messages.

In v1.9.x, nested message types such as `UserScoreRecordItem` were also re-exported in the generated client package. In v1.10.1, only the RPC method input/output types are re-exported.

This may be related to #5481 / #5482 / #5483. I understand that #5481 fixed the issue where each service client generated aliases for all messages from the proto file. However, v1.10.1 seems to only keep direct RPC request/response types and does not include message types transitively used by those request/response messages.

## To Reproduce

Steps to reproduce the behavior, if applicable:

1. The code is:

   ```proto
   syntax = "proto3";

   package userrpc;

   option go_package = "./pb/userrpc";

   service UserScoreRpc {
     rpc UserScoreRecordList(UserScoreRecordListRequest) returns (UserScoreRecordListResponse);
   }

   message UserScoreRecordListRequest {
     int64 user_id = 1;
     int32 page = 2;
     int32 page_size = 3;
   }

   message UserScoreRecordListResponse {
     int64 total = 1;
     repeated UserScoreRecordItem items = 2;
   }

   message UserScoreRecordItem {
     int64 id = 1;
     int64 user_id = 2;
     int32 change_type = 3;
     string actual_score = 4;
     string created_at = 5;
   }
   ```

2. Generate RPC code with goctl v1.10.1.

3. The generated client only contains aliases for direct RPC request/response types:

   ```go
   type (
       UserScoreRecordListRequest  = userrpc.UserScoreRecordListRequest
       UserScoreRecordListResponse = userrpc.UserScoreRecordListResponse
   )
   ```

   But it does not contain:

   ```go
   type (
       UserScoreRecordItem = userrpc.UserScoreRecordItem
   )
   ```

4. The error is:

   ```text
   undefined: userscorerpc.UserScoreRecordItem
   ```

   Existing code that used the generated client package type alias no longer compiles after upgrading from v1.9.x to v1.10.1.

## Expected Behavior

I expected the generated client to include type aliases for message types that are transitively used by this service's RPC request/response messages.

For example, since `UserScoreRecordListResponse` contains:

```proto
repeated UserScoreRecordItem items = 2;
```

I expected the generated client package to also contain:

```go
type (
    UserScoreRecordItem = userrpc.UserScoreRecordItem
)
```

At the same time, I agree that unrelated messages from other services should not be generated into this client package.

So the expected behavior is probably: collect aliases from the service's request/response message dependency graph, not from all proto messages and not only from direct RPC request/response types.

## Screenshots

Not applicable.

## Environments

- OS: Linux
- go-zero version: v1.10.1
- goctl version: v1.10.1 linux/amd64

## More Description

Could you please confirm whether the v1.10.1 behavior is intentional?

Should future versions require users to import nested/shared message types directly from the pb package, for example:

```go
import pb "xxx/pb/userrpc"

item := &pb.UserScoreRecordItem{}
```

Or is this a regression introduced by the per-service type alias filtering change, and should the generator recursively collect message dependencies from each service's request/response types?

From the v1.10.1 generator logic, it looks like the per-service filtering only collects `rpc.RequestType` and `rpc.ReturnsType`, but does not recursively collect message types referenced by fields inside those request/response messages.
